acc/urls.py
from django.urls import path
from . import views

app_name = 'acc'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('profile/', views.profile, name='profile'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
]

book/urls.py
from django.urls import path
from . import views

app_name = 'book'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('create/', views.create, name='create')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include('acc.urls')),
    path('board/', include('board.urls')),
    path('trans/', include('trans.urls')),
    path('pdfread/', include('pdfread.urls')),
    path('vote/', include('vote.urls')),
    path('book/', include('book.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vote/urls.py
from django.urls import path
from . import views

app_name = 'vote'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('detail/<vpk>', views.detail, name='detail'),
    path('vote/<vpk>', views.vote, name='vote'),
    path('cancel/<vpk>', views.cancel, name='cancel'),
    path('create/', views.create, name='create')
]

vote/models.py
from django.db import models
from acc.models import User

# Create your models here.
class Topic(models.Model):
    subject = models.CharField(max_length=200)
    maker = models.ForeignKey(User, on_delete=models.CASCADE, related_name="maker")
    content = models.TextField()
    voter = models.ManyToManyField(User, blank=True, related_name="voter")
    pubdate = models.DateTimeField()
    
    def __str__(self):
        return self.subject
    
    def summary(self):
        return f'{self.content[:15]}'
    
class Choice(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    chname = models.CharField(max_length=100)
    chpic = models.ImageField(upload_to="vote/%y")
    chcom = models.TextField()
    choicer = models.ManyToManyField(User, blank=True)
    
    def __str__(self):
        return f'{self.topic}_{self.chname}'

vote/views.py
from django.shortcuts import render, redirect
from .models import Topic, Choice
from django.utils import timezone

# Create your views here.
def index(request):
    t = Topic.objects.all()
    t = t.order_by("-pubdate")
    context = {
        'tset': t
    }
    return render(request, 'vote/index.html', context)

def detail(request, vpk):
    t = Topic.objects.get(id=vpk)
    c = t.choice_set.all()
    context = {
        't': t,
        'cset': c
    }
    return render(request, 'vote/detail.html', context)

def vote(request, vpk):
    t = Topic.objects.get(id=vpk)
    if not request.user in t.voter.all():
        # 토픽에 투표하지 않은 사람들만 종속문장 실행
        t.voter.add(request.user)
        
        cpk = request.POST.get('ch')
        c = Choice.objects.get(id=cpk)
        c.choicer.add(request.user)
    return redirect('vote:detail', vpk)

def cancel(request, vpk):
    t = Topic.objects.get(id=vpk)
    u = request.user
    if u in t.voter.all():
        t.voter.remove(u)
        u.choice_set.get(topic=t).choicer.remove(u) # 유저가 고른 초이스중에 topic이 t인 레코드중에 초이서에서 u를 remove
    return redirect('vote:detail', vpk)

def create(request):
    if request.method == 'POST':
        s = request.POST.get('sub')
        c = request.POST.get('con')

        names = request.POST.getlist('chname')
        files = request.FILES.getlist('chpic')
        comms = request.POST.getlist('chcom')
        if len(names) > 1:
            t = Topic(subject = s, maker = request.user, content = c, pubdate = timezone.now())
            t.save()

            for i, j ,k in zip(names, files, comms):
                Choice(topic = t, chname = i, chpic = j, chcom = k).save()
            return redirect('vote:index')
    return render(request, 'vote/create.html')

templates/vote/create.html
{% extends 'base.html' %}
{% block con %}
    <div class="container mt-5 mb-5" style="font-size: 20px; font-weight: bold; width: 80%;">
        <h1><b>TOPIC 생성</b></h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3 mt-5">
                <label class="form-label">SUBJECT</label>
                <input name="sub" type="text" class="form-control">
            </div>
            <div class="mb-3">
                <label class="form-label">MAKER</label>
                <input type="text" class="form-control" value="{{ user }}" disabled>
            </div>
            <div class="mb-3">
                <label class="form-label">CONTENT</label>
                <textarea name="con" class="form-control" style="height: 100px;"></textarea>
            </div>

            <div>
                <button type="button" onclick="makebogi()"class="btn btn-dark">보기생성</button>
            </div>

            <div class="row" id="here"></div>

            <div class="text-end mt-3">
                <button class="btn btn-dark" class="btn btn-dark lg">TOPIC 생성</button>
            </div>
        </form>
    </div>


    <script>
        function makebogi(){
            d = document.getElementById('here');
            n = document.createElement('div');
            n.setAttribute('class', 'col-lg-6 mt-5');
            n.innerHTML = '<input type="text" name="chname" class="form-control" placeholder="보기명을 입력하세요.">\
                    <input type="file" name="chpic" class="form-control mb-3 mt-3">\
                    <textarea class="form-control" name="chcom" placeholder="보기를 설명해주세요."></textarea>';
            d.appendChild(n);
        }
    </script>


{% endblock %}

templates/vote/detail.html
{% extends 'base.html' %}

{% block con %}
    {% load mathfilters %}
    <div class="container mt-5 mb-5">
        <h1><b>{{t.subject}}</b></h1>
        <div class="text-end mt-3">
            <button type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#ex2">
                POST
            </button>
        </div>
        <div class="row mt-5">
            <div class="col-lg-8">
                <textarea class="form-control" style="height: 300px;" disabled>{{t.content}}</textarea>
            </div>
            <div class="col-lg-4">
                <img src="{{t.maker.getpic}}" width="100%">
                <div class="text-center mt-3">
                    <h4>made by <b>{{t.maker}}</b></h4>
                </div>
            </div>
        </div>
        {% if user in t.voter.all %}
            <div class="row mt-5">
                {% for i in cset %}
                    <div class="col-lg-4">
                        <img src="{{i.chpic.url}}" width="100%">
                        <div class="text-center mt-3">
                            <h5><b>{{i.chname}}</b></h5>
                        </div>
                        <textarea class="form-control" disabled>{{i.chcom}}</textarea>
                        <div class="progress mt-3 mb-3">
                            <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: {{ i.choicer.all.count | div:t.voter.all.count | mul:100 }}%">{{ i.choicer.all.count | div:t.voter.all.count | mul:100 }}%</div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="text-end mt-4">
                <a href="{% url 'vote:cancel' t.id %}" class="btn btn-dark btn-lg">투표취소</a>
            </div>
        {% else %}
            <form method="post" action="{% url 'vote:vote' t.id %}">
                {% csrf_token %}
                <div class="row mt-5">
                    {% for i in cset %}
                        <div class="col-lg-4">
                            <input class="form-check-input mb-3" type="radio" name="ch" value="{{i.id}}" {% if forloop.first %}checked{% endif %}>
                            <img src="{{i.chpic.url}}" width="100%">
                            <div class="text-center mt-3">
                                <h5><b>{{i.chname}}</b></h5>
                            </div>
                            <textarea class="form-control" disabled>{{i.chcom}}</textarea>
                        </div>
                    {% endfor %}
                </div>
                <div class="text-end mt-4">
                    <button class="btn btn-dark btn-lg">투표하기</button>
                </div>
            </form>
        {% endif %}
    </div>

    <div class="modal fade" id="ex2" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">북마크 추가 알림</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form method="post" action="{% url 'book:create' %}">
                    {% csrf_token %}
                    <div class="modal-body">
                        <div class="text-end">
                            <div class="btn-group" role="group" aria-label="Basic checkbox toggle button group">
                                <input type="checkbox" name="impo" class="btn-check" id="btncheck2" autocomplete="off">
                                <label class="btn btn-outline-warning" for="btncheck2">★</label>
                            </div>
                        </div>
                        <input type="hidden" name="sname" value="[VOTE]{{t.subject}}">
                        <input type="hidden" name="surl" value="{{request.path}}">
                        <b>사이트 설명</b> <input type="text" name="scom" class="form-control mt-2">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
                        <button class="btn btn-primary">북마크 추가</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

templates/vote/index.html
{% extends 'base.html' %}

{% block con %}
    <div class="container mt-5 mb-5">
        <h1><b>투표소</b></h1>

        <div class="text-end">
            <a href="{% url 'vote:create' %}" class="btn btn-success">TOPIC 생성</a>
        </div>

        <div class="row">
            {% for i in tset %}
                <div class="col-lg-4">
                    <div class="card" style="width: 18rem;">
                        <img src="{{i.maker.getpic}}" class="card-img-top" alt="...">
                        <div class="card-body"{% if user in i.voter.all %}style="background-color: aqua;"{% endif %}>
                            <h4 class="card-title"><b>{{i.subject}}</b></h4>
                            <p class="card-text">{{i.summary}}</p>
                            <div class="text-center">
                                <a href="{% url 'vote:detail' i.id %}" class="btn btn-primary">{% if user in i.voter.all %}결과보기{% else %}투표하기{% endif %}</a>
                            </div>
                        </div>
                      </div>
                </div>
            {% endfor %}
        </div>

    </div>

{% endblock %}