acc/urls.py
from django.urls import path
from . import views

app_name = 'acc'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('profile/', views.profile, name='profile'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
]

board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('detail/<bpk>', views.detail, name='detail'),
    path('delete/<bpk>', views.delete, name='delete'),
    path('create/', views.create, name='create'),
    path('update/<bpk>', views.update, name='update'),
    path('creply/<bpk>', views.creply, name='creply'),
    path('dreply/<bpk>/<rpk>', views.dreply, name='dreply'),
    path('likey/<bpk>', views.likey, name="likey"),
    path('lieky/<bpk>', views.cancel, name='cancel')
]

book/urls.py
from django.urls import path
from . import views

app_name = 'book'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('create/', views.create, name='create')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include('acc.urls')),
    path('board/', include('board.urls')),
    path('trans/', include('trans.urls')),
    path('pdfread/', include('pdfread.urls')),
    path('vote/', include('vote.urls')),
    path('book/', include('book.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board/models.py
from django.db import models
from acc.models import User

# Create your models here.
class Board(models.Model):
    subject = models.CharField(max_length=100)
    writer = models.ForeignKey(User, on_delete=models.CASCADE, related_name='writer')
    content = models.TextField()
    likey = models.ManyToManyField(User, blank=True, related_name='likey')
    pubdate = models.DateTimeField()

    def __str__(self):
        return f'{self.subject}'

    def summary(self):
        if len(self.content) > 100:
            return f"{self.content[:100]} ..."
        return f"{self.content}"

class Reply(models.Model):
    b = models.ForeignKey(Board, on_delete=models.CASCADE)
    replier = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField()
    pubdate = models.DateTimeField()

    def __str__(self):
        return f'{self.b}_{self.replier}'

board/views.py
from django.shortcuts import render, redirect
from .models import Board, Reply
from django.utils import timezone
from django.core.paginator import Paginator
from django.contrib import messages

# Create your views here.
def index(request):
    pg = request.GET.get('page', 1)
    cate = request.GET.get('cate', '')
    kw = request.GET.get('kw', '')

    if kw:
        if cate == "sub":
            b = Board.objects.filter(subject__startswith=kw)
        elif cate == "wri":
            from acc.models import User
            try:
                u = User.objects.get(username=kw)
                b = Board.objects.filter(writer=u)
            except:
                b = Board.objects.none()
        elif cate == "con":
            b = Board.objects.filter(content__contains=kw)
        else:
            b = Board.objects.all()
    else:
        b = Board.objects.all()

    b = b.order_by("-pubdate")
    pag = Paginator(b, 10)
    obj = pag.get_page(pg)

    context = {
        "bset": obj,
        'cate': cate,
        'kw': kw
    }
    return render(request, 'board/index.html', context)

def detail(request, bpk):
    b = Board.objects.get(id=bpk)
    r = b.reply_set.all()
    context = {
        'b': b,
        'rset': r
    }
    return render(request, 'board/detail.html', context)

def delete(request, bpk):
    b = Board.objects.get(id=bpk)
    if request.user == b.writer:
        b.delete()
    else:
        messages.error(request, '오류')
    return redirect('board:index')

def create(request):
    if request.method == 'POST':
        s = request.POST.get('psub')
        c = request.POST.get('pcon')
        if s and c:
            Board(subject = s, writer = request.user, content = c, pubdate = timezone.now()).save()
            return redirect('board:index')
    return render(request, 'board/create.html')

def update(request, bpk):
    b = Board.objects.get(id=bpk)
    if b.writer != request.user:
        messages.error(request, '오류')
        return redirect('board:index')
    if request.method == 'POST':
        s = request.POST.get('usub')
        c = request.POST.get('ucon')
        b.subject = s
        b.content = c
        b.save()
        return redirect('board:detail', bpk)
    context = {
        'b': b
    }
    return render(request, 'board/update.html', context)

def creply(request, bpk):
    c = request.POST.get('com')
    b = Board.objects.get(id=bpk)
    Reply(b = b, replier = request.user, comment = c, pubdate = timezone.now()).save()
    return redirect('board:detail', bpk)

def dreply(request, bpk, rpk):
    r = Reply.objects.get(id=rpk)
    if request.user == r.replier:
        r.delete()
    else:
        messages.error(request, '오류')
    return redirect('board:detail', bpk)

def likey(request, bpk):
    b = Board.objects.get(id=bpk)
    b.likey.add(request.user)
    return redirect('board:detail', bpk)

def cancel(request, bpk):
    b = Board.objects.get(id=bpk)
    b.likey.remove(request.user)
    return redirect('board:detail', bpk)

templates/board/create.html
{% extends 'base.html' %}

{% block con %}
    <div class="container mt-5 mb-5" style="font-size: 20px; font-weight: bold; width: 80%;">
        <h1><b>게시글 작성</b></h1>
        <form method="post">
            {% csrf_token %}
            <div class="mb-3 mt-5">
                <label class="form-label">SUBJECT</label>
                <input type="text" name="psub" class="form-control">
            </div>
            <div class="mb-3">
                <label class="form-label">WRITER</label>
                <input type="text" class="form-control" value="{{ user }}" disabled>
            </div>
            <div class="mb-3">
                <label class="form-label">CONTENT</label>
                <textarea class="form-control" name="pcon" style="height: 100px;"></textarea>
            </div>
            <div class="text-end mt-3">
                <button class="btn btn-dark">생성</button>
            </div>
        </form>
    </div>
{% endblock %}

templates/board/detail.html
{% extends 'base.html' %}
{% block con %}
    <div class="container mt-5 mb-5" style="width:70%">
        <h1><b>{{ b.subject }}</b></h1>

        <div class="row mt-5">
            <div class="col-lg-8">
                <textarea class="form-control" style="height: 300px;" disabled>{{ b.content }}</textarea>
            </div>
            <div class="col-lg-4" style="margin: auto;">
                <img src="{{ b.writer.getpic }}" width="100%">
                <div style="font-size: 23px;" class="mt-3 text-center">
                    written by <b>{{b.writer}}</b>
                </div>
                <div class="mt-2 text-end">
                    {{ b.pubdate | date:'Y.m.d. H:i'}}
                </div>
            </div>
        </div>

        <div class="text-end mt-4">
            <a href="{% url 'board:index' %}" class="btn btn-dark btn-lg">BACK</a>
            {% if b.writer == user %}
                <a href="{% url 'board:update' b.id %}" class="btn btn-secondary btn-lg">MOD</a>
                <button type="button" class="btn btn-danger btn-lg" data-bs-toggle="modal" data-bs-target="#ex1">
                    DEL
                </button>
            {% endif %}
        </div>
        
        <div class="text-end mt-3 mb-5">
            {% if user in b.likey.all %}
                <a href="{% url 'board:cancel' b.id %}" class="btn btn-danger btn-lg">CANCEL</a>
            {% else %}
                <a href="{% url 'board:likey' b.id %}" class="btn btn-primary btn-lg">LIKEY</a>
            {% endif %}

            <button type="button" class="btn btn-warning btn-lg" data-bs-toggle="modal" data-bs-target="#ex2">
                POST
            </button>
        </div>

        <hr>

        <form method="post" action="{% url 'board:creply' b.id %}">
            {% csrf_token %}
            <div class="row">
                <div class="col-lg-10">
                    <input type="text" name="com" class="form-control" placeholder="댓글을 남겨주세요">
                </div>
                <div class="col-lg-2">
                    <button class="btn btn-dark">댓글생성</button>
                </div>
            </div>
        </form>
        
        
            <div>
                {% if rset %}
                    {% for i in rset %}
                        <div class="row mt-4">
                            <div class="col-lg-4 text-center">
                                <img src="{{ i.replier.getpic }}" width="100%">
                                <div class="mt-3">
                                    <b>{{ i.replier }}</b>
                                </div>
                            </div>
                            <div class="col-lg-8" style="margin: auto;">
                                <textarea class="form-control" style="height: 100px;" disabled>{{ i.comment }}</textarea>
                                <div class="text-end mt-3">
                                    {% if i.replier == user %}
                                        <a href="{% url 'board:dreply' b.id i.id %}"><button class="btn btn-danger btn-sn">댓글삭제</button></a> 
                                    {% else %}
                                        <a href="#"><button class="btn btn-dark btn-sn">추천하기</button></a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <h1>첫번째 댓글을 달아주세요.</h1>
                {% endif %}
            </div>
            
            <div class="row mt-5 mb-5">
                <div class="col-lg-2">
                    <select class="form-select" aria-label="Default select example">
                        <option>제목</option>
                        <option>글쓴이</option>
                        <option>내용</option>
                    </select>
                </div>
                <div class="col-lg-9">
                    <input type="text" class="form-control">
                </div>
                <div class="col-lg-1">
                    <button class="btn btn-dark">검색</button>
                </div>
            </div>

    </div>



    <!-- 모달창 -->
    <div class="modal fade" id="ex1" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">게시글 삭제 알림</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    정말로 삭제하시겠습니까?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
                    <a href="{% url 'board:delete' b.id %}"><button type="button" class="btn btn-danger">삭제</button></a>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="ex2" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">북마크 추가 알림</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form method="post" action="{% url 'book:create' %}">
                    {% csrf_token %}
                    <div class="modal-body">
                        <div class="text-end">
                            <div class="btn-group" role="group" aria-label="Basic checkbox toggle button group">
                                <input type="checkbox" name="impo" class="btn-check" id="btncheck2" autocomplete="off">
                                <label class="btn btn-outline-warning" for="btncheck2">★</label>
                            </div>
                        </div>
                        <input type="hidden" name="sname" value="[게시판]{{b.subject}}">
                        <input type="hidden" name="surl" value="{{request.path}}">
                        <b>사이트 설명</b> <input type="text" name="scom" class="form-control mt-2">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
                        <button class="btn btn-primary">북마크 추가</button>
                    </div>
                </form>
            </div>
        </div>
    </div>


{% endblock %}

templates/board/index.html
{% extends 'base.html' %}

{% block con %}

{% load mathfilters %}

    <div class="container mt-5" style="width:70%">
        <h1><b>게시판</b></h1>

        <div class="text-end">
            <a href="{% url 'board:create' %}" class="btn btn-dark">게시글 생성</a>
        </div>

        <table class="table mt-3 table-hover">
            <thead>
                <tr>
                    <th scope="col">NO</th>
                    <th scope="col">SUBJECT</th>
                    <th scope="col">SUMMARY</th>
                    <th scope="col">WRITER</th>
                    <th scope="col">LIKEY</th>
                </tr>
            </thead>
            <tbody>
                {% if bset %}
                    {% for i in bset %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td><a class="sub" href="{% url 'board:detail' i.id %}">{{ i.subject }}</a></td>
                            <td>{{ i.summary }}</td>
                            <td>{{ i.writer.username }}</td>
                            <td>{{ i.likey.all.count }}</td>
                        </tr>
                    {% endfor %}
                {% else %}
                    {% if kw %}
                        <tr>
                            <th colspan="5">검색결과가 없습니다.</th>
                        </tr>
                    {% else %}
                        <tr>
                            <th colspan="5">첫번째 게시글을 작성해주세요.</th>
                        </tr>
                    {% endif %}
                {% endif %}
            </tbody>
        </table>

        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                {% if bset.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="{% url 'board:index' %}?page=1&cate={{cate}}&kw={{kw}}">Home</a></li>
                    <li class="page-item">
                        <a class="page-link" href="{% url 'board:index' %}?page={{ bset.previous_page_number }}&cate={{cate}}&kw={{kw}}">Previous</a></li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link">Home</a></li>
                    <li class="page-item disabled">
                        <a class="page-link">Previous</a></li>
                {% endif %}
                
                {% for i in bset.paginator.page_range %}
                    {% if i >= bset.number|sub:5 and bset.number|add:4 >= i %}
                    <li class="page-item {% if bset.number == i %}active{% endif %}"><a class="page-link" href="{% url 'board:index' %}?page={{i}}&cate={{cate}}&kw={{kw}}">{{i}}</a></li>
                    {% endif %}
                {% endfor %}
                
                {% if bset.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="{% url 'board:index' %}?page={{ bset.next_page_number }}&cate={{cate}}&kw={{kw}}">Next</a></li>
                    <li class="page-item">
                        <a class="page-link" href="{% url 'board:index' %}?page={{ bset.paginator.num_pages }}&cate={{cate}}&kw={{kw}}">Last</a></li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link">Next</a></li>
                    <li class="page-item disabled">
                        <a class="page-link">Last</a></li>
                {% endif %}
            </ul>
        </nav>

        <form>
            <div class="row mt-5 mb-5">
                <div class="col-lg-2">
                    <select name="cate" class="form-select" aria-label="Default select example">
                        <option value="sub" {% if cate == 'sub' %}selected{% endif %}>제목</option>
                        <option value="wri" {% if cate == 'wri' %}selected{% endif %}>글쓴이</option>
                        <option value="con" {% if cate == 'con' %}selected{% endif %}>내용</option>
                    </select>
                </div>
                <div class="col-lg-9">
                    <input name="kw" type="text" size="50" value='{{kw}}' class="form-control">
                </div>
                <div class="col-lg-1">
                    <button class="btn btn-dark">검색</button>
                </div>
            </div>
        </form>

    </div>
    


    <style>
        a.sub {
            text-decoration: none;
            color:black;
            font-weight: bold;
            font-size: 17px;
        }
        a.sub:hover {
            color:red;
            font-size:18px;
        }
    </style>

{% endblock %}

templates/board/update.html
{% extends 'base.html' %}

{% block con %}
    <div class="container mt-5 mb-5" style="font-size: 20px; font-weight: bold; width: 80%;">
        <h1><b>게시글수정</b></h1>
        <form method="post">
            {% csrf_token %}
            <div class="mb-3 mt-5">
                <label class="form-label">SUBJECT</label>
                <input type="text" name="usub" value="{{ b.subject }}" class="form-control">
            </div>
            <div class="mb-3">
                <label class="form-label">WRITER</label>
                <input type="text" value="{{ b.writer }}" class="form-control" disabled>
            </div>
            <div class="mb-3">
                <label class="form-label">CONTENT</label>
                <textarea class="form-control" name="ucon" style="height: 100px;">{{ b.content }}</textarea>
            </div>
            <div class="text-end mt-3">
                <button class="btn btn-dark">수정하기</button>
            </div>
        </form>
    </div>
{% endblock %}